Included the audio file's path with the returned tags
We might want our (`onSuccess`) callback function to also return the `path` of the audio file it read along with its `tags`. So that we can properly construct the following track object for example;

```js
conts jsm = require('jsmediatags')

new jsm.Reader('/path/to/file').setTagsToRead(['
    title', 'artist', 'album', 'genre', 'picture', 'year'
]).read({
    onSuccess: (tag, path) => {
        var raw_title = path.slice(path.lastIndexOf('/')+1, path.length)
        raw_title = raw_title.split('.')[0]

        var track = {
            title: !tag.tags.title ? raw_title : tag.tags.title,
            artist: !tag.tags.artist ? 'Unknown' : tag.tags.artist,
            source: path,
            // ...
        }

       // Then maybe we can call some function to play the track; `this.playTrack(track.source)`
       // ... and possibly use the info from the tags to render the track's info like the title, artist, etc

    },
    onError: (error) => {
        console.debug(error)   
    }
})
```